const fs=require('fs'),path=require('path');
const qs=JSON.parse(fs.readFileSync(path.join(__dirname,'..','data','questions.json'),'utf8'));
const norm=s=>String(s||'').toLocaleLowerCase('sv-SE').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9åäö ]/g,' ').replace(/\s+/g,' ').trim();
const stop=new Set('vilken vilket vilka vad vem var när hur och eller som det den ett en är av på i till för med från'.split(' '));
const tokens=s=>new Set(norm(s).split(' ').filter(x=>x.length>3&&!stop.has(x)));
const issues=[]; const keys=new Map();
for(const q of qs){const p=[]; if(!q.q?.trim().endsWith('?')&&!/^(sant eller falskt|ordna|sortera)/i.test(q.q||''))p.push('punctuation'); if((q.q||'').length<12)p.push('too-short'); if((q.q||'').length>240)p.push('too-long'); if(!Array.isArray(q.a)||q.a.length<2)p.push('options'); if(new Set((q.a||[]).map(norm)).size!==(q.a||[]).length)p.push('duplicate-options'); if(q.r<0||q.r>=(q.a||[]).length)p.push('answer-index'); const k=norm(q.q); if(keys.has(k)&&!q.visual&&!q.audio)p.push('repeated-prompt'); else if(!q.visual&&!q.audio)keys.set(k,q.id); if(/\b(idag|just nu|nuvarande|senaste|i år)\b/i.test(q.q||''))p.push('time-sensitive'); if(p.length)issues.push({id:q.id,category:q.c,text:q.q,issues:p});}
// conservative near-duplicate candidates: same category, same first 4 meaningful tokens
const buckets=new Map();for(const q of qs){const t=[...tokens(q.q)].slice(0,4);if(t.length<3)continue;const k=(q.c||'')+'|'+t.sort().join('|');const a=buckets.get(k)||[];a.push(q);buckets.set(k,a)}
const near=[];for(const a of buckets.values())if(a.length>1)for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length;j++){const A=tokens(a[i].q),B=tokens(a[j].q),inter=[...A].filter(x=>B.has(x)).length,union=new Set([...A,...B]).size,sim=union?inter/union:0;if(sim>=.88&&Math.min((a[i].q||'').length,(a[j].q||'').length)/Math.max((a[i].q||'').length,(a[j].q||'').length)>=.75&&norm(a[i].q)!==norm(a[j].q))near.push({a:a[i].id,b:a[j].id,similarity:+sim.toFixed(2),qa:a[i].q,qb:a[j].q})}
const report={generatedAt:new Date().toISOString(),questions:qs.length,issues:issues.length,nearDuplicateCandidates:near.length,issueBreakdown:{},items:issues,nearDuplicates:near.slice(0,1000)};for(const x of issues)for(const i of x.issues)report.issueBreakdown[i]=(report.issueBreakdown[i]||0)+1;fs.writeFileSync(path.join(__dirname,'..','data','semantic-quality-audit.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({ok:true,questions:qs.length,issues:issues.length,nearDuplicateCandidates:near.length,breakdown:report.issueBreakdown}));if(issues.some(x=>x.issues.includes('answer-index')||x.issues.includes('options')||x.issues.includes('duplicate-options')))process.exit(1);
