'use strict';
// Runtime smoke test intended for the installed app. It exercises real HTTP endpoints
// against a temporary Quiz process and fails fast on missing core flows.
const {spawn}=require('child_process');const fs=require('fs'),path=require('path'),os=require('os');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'quiz22-smoke-')),port=31991,root=path.join(__dirname,'..');
for(const f of ['questions.json','results.json','users.json','settings.json','question-reports.json'])fs.copyFileSync(path.join(root,'data',f),path.join(tmp,f));
const child=spawn(process.execPath,['server.js'],{cwd:root,env:{...process.env,PORT:String(port),HOST:'127.0.0.1',RESEQUIZ_DATA_DIR:tmp},stdio:['ignore','pipe','pipe']});
const base=`http://127.0.0.1:${port}`;const wait=ms=>new Promise(r=>setTimeout(r,ms));async function json(url,opt){const r=await fetch(base+url,opt);if(!r.ok)throw new Error(`${url}: HTTP ${r.status}`);return r.json()}
(async()=>{try{for(let i=0;i<50;i++){try{const h=await json('/health');if(h.version==='23.0.0')break}catch{}await wait(100)}const health=await json('/health');if(health.version!=='23.0.0')throw new Error('wrong version');const meta=await json('/api/meta');if(!meta.categories?.length)throw new Error('no categories');const daily=await json('/api/daily');if(!daily.questions?.length)throw new Error('daily empty');const solo=await json('/api/solo/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({count:5})});if(solo.questions?.length!==5)throw new Error('solo start failed');const q=solo.questions[0];const check=await json('/api/solo/check',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({questionId:q.id,answerIndex:0,responseMs:1200})});if(typeof check.correct!=='boolean')throw new Error('solo check failed');const duel=await json('/api/duels',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Smoke',count:5})});const duelRead=await json(`/api/duels/${duel.duel.id}`);if(duelRead.duel.questions.length!==5)throw new Error('duel failed');console.log('Quiz 23 smoke E2E: OK')}catch(e){console.error('Quiz 23 smoke E2E: FAIL',e);process.exitCode=1}finally{child.kill('SIGTERM');setTimeout(()=>process.exit(process.exitCode||0),100)}})();
